"""add fio and rename column

Revision ID: 423e999dfd53
Revises: 25fbdfa191ef
Create Date: 2024-12-02 20:37:41.180047

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "423e999dfd53"
down_revision: Union[str, None] = "25fbdfa191ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=200), nullable=False))
    op.add_column("users", sa.Column("fio", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "email_verified")
    op.drop_column("users", "fio")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
