"""change code type

Revision ID: 65685b4964a2
Revises: d153e6388403
Create Date: 2024-12-06 22:03:02.842032

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65685b4964a2"
down_revision: Union[str, None] = "d153e6388403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verification_codes",
        "code",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verification_codes",
        "code",
        existing_type=sa.String(length=10),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
