"""change user model

Revision ID: 7961e40e09b2
Revises: 278926825c85
Create Date: 2024-12-06 15:42:00.962289

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7961e40e09b2"
down_revision: Union[str, None] = "278926825c85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=200), nullable=False))
    op.add_column(
        "users", sa.Column("patronymic", sa.String(length=200), nullable=False)
    )
    op.add_column("users", sa.Column("surname", sa.String(length=200), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(length=200), nullable=False))
    op.add_column(
        "users", sa.Column("date_of_birth", sa.String(length=200), nullable=False)
    )
    op.add_column("users", sa.Column("role", sa.String(length=200), nullable=False))
    op.add_column("users", sa.Column("is_email_verified", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("updated_at", sa.String(length=200), nullable=True)
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.drop_column("users", "fio")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email_verified", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "password_hash", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("fio", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.String(length=200),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_column("users", "updated_at")
    op.drop_column("users", "is_email_verified")
    op.drop_column("users", "role")
    op.drop_column("users", "date_of_birth")
    op.drop_column("users", "password")
    op.drop_column("users", "surname")
    op.drop_column("users", "patronymic")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
