"""cascade delete

Revision ID: 278926825c85
Revises: 16fb74be35f6
Create Date: 2024-12-06 13:52:06.288459

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278926825c85"
down_revision: Union[str, None] = "16fb74be35f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_verification_codes_users_id_user", "verification_codes", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_verification_codes_users_id_user",
        "verification_codes",
        "users",
        ["user"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_verification_codes_users_id_user", "verification_codes", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_verification_codes_users_id_user",
        "verification_codes",
        "users",
        ["user"],
        ["id"],
    )
    # ### end Alembic commands ###
