"""change nullable column

Revision ID: 5311554e97c7
Revises: 2f1f00113717
Create Date: 2024-12-07 22:08:02.732407

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5311554e97c7"
down_revision: Union[str, None] = "2f1f00113717"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "regional_agents",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        nullable=True,
    )
    op.alter_column(
        "regional_agents",
        "address",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.alter_column(
        "regional_agents",
        "telegram",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.alter_column(
        "regional_agents", "vk", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column(
        "regional_agents", "email", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column(
        "regional_agents",
        "phone_number",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "regional_agents",
        "phone_number",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "regional_agents", "email", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "regional_agents", "vk", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "regional_agents",
        "telegram",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "regional_agents",
        "address",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "regional_agents",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        nullable=False,
    )
    # ### end Alembic commands ###
