"""add and rename column

Revision ID: 16fb74be35f6
Revises: 37774b0aaf2d
Create Date: 2024-12-05 17:32:30.949921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "16fb74be35f6"
down_revision: Union[str, None] = "37774b0aaf2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_codes",
        sa.Column("send_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "verification_codes",
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("verification_codes", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_codes",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("verification_codes", "expired_at")
    op.drop_column("verification_codes", "send_at")
    # ### end Alembic commands ###
