"""rewrite models again

Revision ID: 2f1f00113717
Revises: 65685b4964a2
Create Date: 2024-12-07 12:25:03.965085

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f1f00113717"
down_revision: Union[str, None] = "65685b4964a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regional_agents", sa.Column("fio", sa.String(length=200), nullable=True)
    )
    op.drop_constraint(
        "fk_regional_agents_users_id_user_id", "regional_agents", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_regional_agents_users_id_user_id",
        "regional_agents",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("regional_agents", "status")
    op.add_column("users", sa.Column("status", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    op.add_column(
        "regional_agents",
        sa.Column("status", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fk_regional_agents_users_id_user_id", "regional_agents", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_regional_agents_users_id_user_id",
        "regional_agents",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("regional_agents", "fio")
    # ### end Alembic commands ###
