"""add new columns

Revision ID: b8990dceb599
Revises: 5311554e97c7
Create Date: 2024-12-07 23:02:10.880800

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8990dceb599"
down_revision: Union[str, None] = "5311554e97c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regional_agents", sa.Column("iso_code", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "regional_agents",
        sa.Column("region_emblem_url", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regional_agents", "region_emblem_url")
    op.drop_column("regional_agents", "iso_code")
    # ### end Alembic commands ###
