"""add regional agent table

Revision ID: 84d77f110e99
Revises: 7961e40e09b2
Create Date: 2024-12-06 17:26:07.717744

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84d77f110e99"
down_revision: Union[str, None] = "7961e40e09b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regional_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("federal_subject", sa.String(length=200), nullable=False),
        sa.Column("telegram", sa.String(length=200), nullable=False),
        sa.Column("vk", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("phone_number", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.String(length=200), nullable=True),
        sa.Column("updated_at", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_regional_agents_users_id_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("regional_agents")
    # ### end Alembic commands ###
